### ISSUE TITLE
Ad doesn't load randomly

### ISSUE THREAD

**Issue by steven5210** [seeden/react-google-publisher-tag#10]
I've been debugging it and for some reason sometimes the ad doesn't render at all. It happens pretty randomly but sometimes it seems to happen as soon as the page loads when I scroll to the bottom or out of view of the ad. I checked the element and it seems like it sets to `height` to `auto` and then `0`. I'm currently passing in the `path` and the `dimensions`. Would you happen to know what could be causing the issue? Thanks!

![image](https://cloud.githubusercontent.com/assets/10110177/24771418/63a2f7a0-1ac2-11e7-95a7-de0cc0967c67.png)

**Comment by seeden** [comment]
If your webpage is fresh or you have started to use adsense few hours ago. Google is not showing ad sometimes. This is normal behaviour. It will be fine in few hours (days)

**Comment by steven5210** [comment]
Thanks for the quick response! This behavior has been happening on our QA build of the site lately. Is this an issue that happens every time a new build happens for our site by chance? Thanks again!

**Comment by seeden** [comment]
I don't know. I have no problem with it for few years. I had this problem when my webpage was not visible for google and it had no idea what to show. Google sometimes has no ad. You need to allow google fetch your url and wait few hours

**Comment by steven5210** [comment]
Thanks for the answers!
