### ISSUE TITLE
Ad Refresh

### ISSUE THREAD

**Issue by trakout** [seeden/react-google-publisher-tag#2]
Wondering, did you have any plans for refreshSlot()?

**Comment by seeden** [comment]
Hi @trakout 
There is this option already
you can use ref here is small example

``` js
export default Example extends Component {
  refresh() {
    this.refs.ad1.refreshSlot();
  }

  render() {
    return(
      <AD path="/network-code/ad-code" ref="ad1" />
    );
  }
}
```

**Comment by trakout** [comment]
@seeden awesome, thanks!

**Comment by anhdn** [comment]
Hi @seeden , can i change targeting object when i use "this.refs.ad1.refreshSlot()"?
