### ISSUE TITLE
Ad render or gets refreshed repeatedly

### ISSUE THREAD

**Issue by k-prashant** [seeden/react-google-publisher-tag#22]
I have an page where content is loaded in continuous scroll i.e. new content is appended to previous one. So I have master div in which this contents get added, and each content has unique ad codes. Whenever a new content is added to master div, it renders all data including previous content with its ad codes, but this page does not get hard refresh. So, can you let me know how to prevent complete ad refresh behaviour.

**Comment by seeden** [comment]
are you sure that you are not doing component unmount? verify it

**Comment by k-prashant** [comment]
Have checked it, component does not unmount or mount repeatedly. Even tried appending key to it, but still all ads refreshes repeatedly.

**Comment by k-prashant** [comment]
I have made changes at my master component and added key as well as ref and used it to prevent adcodes refresh. It worked, and also added shouldComponentUpdate check.
